//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Listas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public int CODCLI { get; set; }
        public string NOME { get; set; }
        public string FANTASIA { get; set; }
        public string ENDERECO { get; set; }
        public string BAIRRO { get; set; }
        public string CIDADE { get; set; }
        public string ESTADO { get; set; }
        public string CEP { get; set; }
        public string END_COB { get; set; }
        public string BAI_COB { get; set; }
        public string CID_COB { get; set; }
        public string EST_COB { get; set; }
        public string CEP_COB { get; set; }
        public string CNPJ { get; set; }
        public string INSCRICAO { get; set; }
        public string FONE1 { get; set; }
        public string FAX { get; set; }
        public string E_MAIL { get; set; }
        public Nullable<System.DateTime> DATA_CAD { get; set; }
        public Nullable<double> ICMS { get; set; }
        public string REVENDA_CONSUMIDOR { get; set; }
    }
}
