#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Listas
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Pedidos")]
	public partial class PedidosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCLIENTE(CLIENTE instance);
    partial void UpdateCLIENTE(CLIENTE instance);
    partial void DeleteCLIENTE(CLIENTE instance);
    partial void InsertPEDIDO(PEDIDO instance);
    partial void UpdatePEDIDO(PEDIDO instance);
    partial void DeletePEDIDO(PEDIDO instance);
    partial void InsertVENDEDORE(VENDEDORE instance);
    partial void UpdateVENDEDORE(VENDEDORE instance);
    partial void DeleteVENDEDORE(VENDEDORE instance);
    partial void InsertITENSPEDIDO(ITENSPEDIDO instance);
    partial void UpdateITENSPEDIDO(ITENSPEDIDO instance);
    partial void DeleteITENSPEDIDO(ITENSPEDIDO instance);
    partial void InsertPRODUTO(PRODUTO instance);
    partial void UpdatePRODUTO(PRODUTO instance);
    partial void DeletePRODUTO(PRODUTO instance);
    partial void InsertTIPOPRODUTO(TIPOPRODUTO instance);
    partial void UpdateTIPOPRODUTO(TIPOPRODUTO instance);
    partial void DeleteTIPOPRODUTO(TIPOPRODUTO instance);
    #endregion
		
		public PedidosDataContext() : 
				base(global::Listas.Properties.Settings.Default.PedidosConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PedidosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PedidosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PedidosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PedidosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CLIENTE> CLIENTEs
		{
			get
			{
				return this.GetTable<CLIENTE>();
			}
		}
		
		public System.Data.Linq.Table<PEDIDO> PEDIDOs
		{
			get
			{
				return this.GetTable<PEDIDO>();
			}
		}
		
		public System.Data.Linq.Table<VENDEDORE> VENDEDOREs
		{
			get
			{
				return this.GetTable<VENDEDORE>();
			}
		}
		
		public System.Data.Linq.Table<ITENSPEDIDO> ITENSPEDIDOs
		{
			get
			{
				return this.GetTable<ITENSPEDIDO>();
			}
		}
		
		public System.Data.Linq.Table<PRODUTO> PRODUTOs
		{
			get
			{
				return this.GetTable<PRODUTO>();
			}
		}
		
		public System.Data.Linq.Table<TIPOPRODUTO> TIPOPRODUTOs
		{
			get
			{
				return this.GetTable<TIPOPRODUTO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLIENTES")]
	public partial class CLIENTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CODCLI;
		
		private string _NOME;
		
		private string _FANTASIA;
		
		private string _ENDERECO;
		
		private string _BAIRRO;
		
		private string _CIDADE;
		
		private string _ESTADO;
		
		private string _CEP;
		
		private string _END_COB;
		
		private string _BAI_COB;
		
		private string _CID_COB;
		
		private string _EST_COB;
		
		private string _CEP_COB;
		
		private string _CNPJ;
		
		private string _INSCRICAO;
		
		private string _FONE1;
		
		private string _FAX;
		
		private string _E_MAIL;
		
		private System.Nullable<System.DateTime> _DATA_CAD;
		
		private System.Nullable<double> _ICMS;
		
		private System.Nullable<char> _REVENDA_CONSUMIDOR;
		
		private EntitySet<PEDIDO> _PEDIDOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODCLIChanging(int value);
    partial void OnCODCLIChanged();
    partial void OnNOMEChanging(string value);
    partial void OnNOMEChanged();
    partial void OnFANTASIAChanging(string value);
    partial void OnFANTASIAChanged();
    partial void OnENDERECOChanging(string value);
    partial void OnENDERECOChanged();
    partial void OnBAIRROChanging(string value);
    partial void OnBAIRROChanged();
    partial void OnCIDADEChanging(string value);
    partial void OnCIDADEChanged();
    partial void OnESTADOChanging(string value);
    partial void OnESTADOChanged();
    partial void OnCEPChanging(string value);
    partial void OnCEPChanged();
    partial void OnEND_COBChanging(string value);
    partial void OnEND_COBChanged();
    partial void OnBAI_COBChanging(string value);
    partial void OnBAI_COBChanged();
    partial void OnCID_COBChanging(string value);
    partial void OnCID_COBChanged();
    partial void OnEST_COBChanging(string value);
    partial void OnEST_COBChanged();
    partial void OnCEP_COBChanging(string value);
    partial void OnCEP_COBChanged();
    partial void OnCNPJChanging(string value);
    partial void OnCNPJChanged();
    partial void OnINSCRICAOChanging(string value);
    partial void OnINSCRICAOChanged();
    partial void OnFONE1Changing(string value);
    partial void OnFONE1Changed();
    partial void OnFAXChanging(string value);
    partial void OnFAXChanged();
    partial void OnE_MAILChanging(string value);
    partial void OnE_MAILChanged();
    partial void OnDATA_CADChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_CADChanged();
    partial void OnICMSChanging(System.Nullable<double> value);
    partial void OnICMSChanged();
    partial void OnREVENDA_CONSUMIDORChanging(System.Nullable<char> value);
    partial void OnREVENDA_CONSUMIDORChanged();
    #endregion
		
		public CLIENTE()
		{
			this._PEDIDOs = new EntitySet<PEDIDO>(new Action<PEDIDO>(this.attach_PEDIDOs), new Action<PEDIDO>(this.detach_PEDIDOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODCLI", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CODCLI
		{
			get
			{
				return this._CODCLI;
			}
			set
			{
				if ((this._CODCLI != value))
				{
					this.OnCODCLIChanging(value);
					this.SendPropertyChanging();
					this._CODCLI = value;
					this.SendPropertyChanged("CODCLI");
					this.OnCODCLIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME", DbType="VarChar(50)")]
		public string NOME
		{
			get
			{
				return this._NOME;
			}
			set
			{
				if ((this._NOME != value))
				{
					this.OnNOMEChanging(value);
					this.SendPropertyChanging();
					this._NOME = value;
					this.SendPropertyChanged("NOME");
					this.OnNOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FANTASIA", DbType="VarChar(20)")]
		public string FANTASIA
		{
			get
			{
				return this._FANTASIA;
			}
			set
			{
				if ((this._FANTASIA != value))
				{
					this.OnFANTASIAChanging(value);
					this.SendPropertyChanging();
					this._FANTASIA = value;
					this.SendPropertyChanged("FANTASIA");
					this.OnFANTASIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDERECO", DbType="VarChar(60)")]
		public string ENDERECO
		{
			get
			{
				return this._ENDERECO;
			}
			set
			{
				if ((this._ENDERECO != value))
				{
					this.OnENDERECOChanging(value);
					this.SendPropertyChanging();
					this._ENDERECO = value;
					this.SendPropertyChanged("ENDERECO");
					this.OnENDERECOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAIRRO", DbType="VarChar(20)")]
		public string BAIRRO
		{
			get
			{
				return this._BAIRRO;
			}
			set
			{
				if ((this._BAIRRO != value))
				{
					this.OnBAIRROChanging(value);
					this.SendPropertyChanging();
					this._BAIRRO = value;
					this.SendPropertyChanged("BAIRRO");
					this.OnBAIRROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIDADE", DbType="VarChar(20)")]
		public string CIDADE
		{
			get
			{
				return this._CIDADE;
			}
			set
			{
				if ((this._CIDADE != value))
				{
					this.OnCIDADEChanging(value);
					this.SendPropertyChanging();
					this._CIDADE = value;
					this.SendPropertyChanged("CIDADE");
					this.OnCIDADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="VarChar(2)")]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this.OnESTADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO = value;
					this.SendPropertyChanged("ESTADO");
					this.OnESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="VarChar(8)")]
		public string CEP
		{
			get
			{
				return this._CEP;
			}
			set
			{
				if ((this._CEP != value))
				{
					this.OnCEPChanging(value);
					this.SendPropertyChanging();
					this._CEP = value;
					this.SendPropertyChanged("CEP");
					this.OnCEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_END_COB", DbType="VarChar(60)")]
		public string END_COB
		{
			get
			{
				return this._END_COB;
			}
			set
			{
				if ((this._END_COB != value))
				{
					this.OnEND_COBChanging(value);
					this.SendPropertyChanging();
					this._END_COB = value;
					this.SendPropertyChanged("END_COB");
					this.OnEND_COBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAI_COB", DbType="VarChar(20)")]
		public string BAI_COB
		{
			get
			{
				return this._BAI_COB;
			}
			set
			{
				if ((this._BAI_COB != value))
				{
					this.OnBAI_COBChanging(value);
					this.SendPropertyChanging();
					this._BAI_COB = value;
					this.SendPropertyChanged("BAI_COB");
					this.OnBAI_COBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CID_COB", DbType="VarChar(20)")]
		public string CID_COB
		{
			get
			{
				return this._CID_COB;
			}
			set
			{
				if ((this._CID_COB != value))
				{
					this.OnCID_COBChanging(value);
					this.SendPropertyChanging();
					this._CID_COB = value;
					this.SendPropertyChanged("CID_COB");
					this.OnCID_COBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EST_COB", DbType="VarChar(2)")]
		public string EST_COB
		{
			get
			{
				return this._EST_COB;
			}
			set
			{
				if ((this._EST_COB != value))
				{
					this.OnEST_COBChanging(value);
					this.SendPropertyChanging();
					this._EST_COB = value;
					this.SendPropertyChanged("EST_COB");
					this.OnEST_COBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP_COB", DbType="VarChar(8)")]
		public string CEP_COB
		{
			get
			{
				return this._CEP_COB;
			}
			set
			{
				if ((this._CEP_COB != value))
				{
					this.OnCEP_COBChanging(value);
					this.SendPropertyChanging();
					this._CEP_COB = value;
					this.SendPropertyChanged("CEP_COB");
					this.OnCEP_COBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNPJ", DbType="VarChar(18)")]
		public string CNPJ
		{
			get
			{
				return this._CNPJ;
			}
			set
			{
				if ((this._CNPJ != value))
				{
					this.OnCNPJChanging(value);
					this.SendPropertyChanging();
					this._CNPJ = value;
					this.SendPropertyChanged("CNPJ");
					this.OnCNPJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSCRICAO", DbType="VarChar(19)")]
		public string INSCRICAO
		{
			get
			{
				return this._INSCRICAO;
			}
			set
			{
				if ((this._INSCRICAO != value))
				{
					this.OnINSCRICAOChanging(value);
					this.SendPropertyChanging();
					this._INSCRICAO = value;
					this.SendPropertyChanged("INSCRICAO");
					this.OnINSCRICAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FONE1", DbType="VarChar(15)")]
		public string FONE1
		{
			get
			{
				return this._FONE1;
			}
			set
			{
				if ((this._FONE1 != value))
				{
					this.OnFONE1Changing(value);
					this.SendPropertyChanging();
					this._FONE1 = value;
					this.SendPropertyChanged("FONE1");
					this.OnFONE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX", DbType="VarChar(15)")]
		public string FAX
		{
			get
			{
				return this._FAX;
			}
			set
			{
				if ((this._FAX != value))
				{
					this.OnFAXChanging(value);
					this.SendPropertyChanging();
					this._FAX = value;
					this.SendPropertyChanged("FAX");
					this.OnFAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_MAIL", DbType="VarChar(35)")]
		public string E_MAIL
		{
			get
			{
				return this._E_MAIL;
			}
			set
			{
				if ((this._E_MAIL != value))
				{
					this.OnE_MAILChanging(value);
					this.SendPropertyChanging();
					this._E_MAIL = value;
					this.SendPropertyChanged("E_MAIL");
					this.OnE_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_CAD", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA_CAD
		{
			get
			{
				return this._DATA_CAD;
			}
			set
			{
				if ((this._DATA_CAD != value))
				{
					this.OnDATA_CADChanging(value);
					this.SendPropertyChanging();
					this._DATA_CAD = value;
					this.SendPropertyChanged("DATA_CAD");
					this.OnDATA_CADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICMS", DbType="Float")]
		public System.Nullable<double> ICMS
		{
			get
			{
				return this._ICMS;
			}
			set
			{
				if ((this._ICMS != value))
				{
					this.OnICMSChanging(value);
					this.SendPropertyChanging();
					this._ICMS = value;
					this.SendPropertyChanged("ICMS");
					this.OnICMSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REVENDA_CONSUMIDOR", DbType="Char(1)")]
		public System.Nullable<char> REVENDA_CONSUMIDOR
		{
			get
			{
				return this._REVENDA_CONSUMIDOR;
			}
			set
			{
				if ((this._REVENDA_CONSUMIDOR != value))
				{
					this.OnREVENDA_CONSUMIDORChanging(value);
					this.SendPropertyChanging();
					this._REVENDA_CONSUMIDOR = value;
					this.SendPropertyChanged("REVENDA_CONSUMIDOR");
					this.OnREVENDA_CONSUMIDORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTE_PEDIDO", Storage="_PEDIDOs", ThisKey="CODCLI", OtherKey="CODCLI")]
		public EntitySet<PEDIDO> PEDIDOs
		{
			get
			{
				return this._PEDIDOs;
			}
			set
			{
				this._PEDIDOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PEDIDOs(PEDIDO entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTE = this;
		}
		
		private void detach_PEDIDOs(PEDIDO entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTE = null;
		}

        internal static void Add(CLIENTE cliente)
        {
            throw new NotImplementedException();
        }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PEDIDOS")]
	public partial class PEDIDO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NUM_PEDIDO;
		
		private System.Nullable<int> _CODCLI;
		
		private System.Nullable<short> _CODVEN;
		
		private System.Nullable<System.DateTime> _DATA_EMISSAO;
		
		private System.Nullable<decimal> _VLR_TOTAL;
		
		private string _SITUACAO;
		
		private string _OBSERVACOES;
		
		private EntitySet<ITENSPEDIDO> _ITENSPEDIDOs;
		
		private EntityRef<CLIENTE> _CLIENTE;
		
		private EntityRef<VENDEDORE> _VENDEDORE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNUM_PEDIDOChanging(int value);
    partial void OnNUM_PEDIDOChanged();
    partial void OnCODCLIChanging(System.Nullable<int> value);
    partial void OnCODCLIChanged();
    partial void OnCODVENChanging(System.Nullable<short> value);
    partial void OnCODVENChanged();
    partial void OnDATA_EMISSAOChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_EMISSAOChanged();
    partial void OnVLR_TOTALChanging(System.Nullable<decimal> value);
    partial void OnVLR_TOTALChanged();
    partial void OnSITUACAOChanging(string value);
    partial void OnSITUACAOChanged();
    partial void OnOBSERVACOESChanging(string value);
    partial void OnOBSERVACOESChanged();
    #endregion
		
		public PEDIDO()
		{
			this._ITENSPEDIDOs = new EntitySet<ITENSPEDIDO>(new Action<ITENSPEDIDO>(this.attach_ITENSPEDIDOs), new Action<ITENSPEDIDO>(this.detach_ITENSPEDIDOs));
			this._CLIENTE = default(EntityRef<CLIENTE>);
			this._VENDEDORE = default(EntityRef<VENDEDORE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUM_PEDIDO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NUM_PEDIDO
		{
			get
			{
				return this._NUM_PEDIDO;
			}
			set
			{
				if ((this._NUM_PEDIDO != value))
				{
					this.OnNUM_PEDIDOChanging(value);
					this.SendPropertyChanging();
					this._NUM_PEDIDO = value;
					this.SendPropertyChanged("NUM_PEDIDO");
					this.OnNUM_PEDIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODCLI", DbType="Int")]
		public System.Nullable<int> CODCLI
		{
			get
			{
				return this._CODCLI;
			}
			set
			{
				if ((this._CODCLI != value))
				{
					if (this._CLIENTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCODCLIChanging(value);
					this.SendPropertyChanging();
					this._CODCLI = value;
					this.SendPropertyChanged("CODCLI");
					this.OnCODCLIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODVEN", DbType="SmallInt")]
		public System.Nullable<short> CODVEN
		{
			get
			{
				return this._CODVEN;
			}
			set
			{
				if ((this._CODVEN != value))
				{
					if (this._VENDEDORE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCODVENChanging(value);
					this.SendPropertyChanging();
					this._CODVEN = value;
					this.SendPropertyChanged("CODVEN");
					this.OnCODVENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_EMISSAO", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA_EMISSAO
		{
			get
			{
				return this._DATA_EMISSAO;
			}
			set
			{
				if ((this._DATA_EMISSAO != value))
				{
					this.OnDATA_EMISSAOChanging(value);
					this.SendPropertyChanging();
					this._DATA_EMISSAO = value;
					this.SendPropertyChanged("DATA_EMISSAO");
					this.OnDATA_EMISSAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VLR_TOTAL", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> VLR_TOTAL
		{
			get
			{
				return this._VLR_TOTAL;
			}
			set
			{
				if ((this._VLR_TOTAL != value))
				{
					this.OnVLR_TOTALChanging(value);
					this.SendPropertyChanging();
					this._VLR_TOTAL = value;
					this.SendPropertyChanged("VLR_TOTAL");
					this.OnVLR_TOTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITUACAO", DbType="VarChar(1)")]
		public string SITUACAO
		{
			get
			{
				return this._SITUACAO;
			}
			set
			{
				if ((this._SITUACAO != value))
				{
					this.OnSITUACAOChanging(value);
					this.SendPropertyChanging();
					this._SITUACAO = value;
					this.SendPropertyChanged("SITUACAO");
					this.OnSITUACAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACOES", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string OBSERVACOES
		{
			get
			{
				return this._OBSERVACOES;
			}
			set
			{
				if ((this._OBSERVACOES != value))
				{
					this.OnOBSERVACOESChanging(value);
					this.SendPropertyChanging();
					this._OBSERVACOES = value;
					this.SendPropertyChanged("OBSERVACOES");
					this.OnOBSERVACOESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PEDIDO_ITENSPEDIDO", Storage="_ITENSPEDIDOs", ThisKey="NUM_PEDIDO", OtherKey="NUM_PEDIDO")]
		public EntitySet<ITENSPEDIDO> ITENSPEDIDOs
		{
			get
			{
				return this._ITENSPEDIDOs;
			}
			set
			{
				this._ITENSPEDIDOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTE_PEDIDO", Storage="_CLIENTE", ThisKey="CODCLI", OtherKey="CODCLI", IsForeignKey=true)]
		public CLIENTE CLIENTE
		{
			get
			{
				return this._CLIENTE.Entity;
			}
			set
			{
				CLIENTE previousValue = this._CLIENTE.Entity;
				if (((previousValue != value) 
							|| (this._CLIENTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLIENTE.Entity = null;
						previousValue.PEDIDOs.Remove(this);
					}
					this._CLIENTE.Entity = value;
					if ((value != null))
					{
						value.PEDIDOs.Add(this);
						this._CODCLI = value.CODCLI;
					}
					else
					{
						this._CODCLI = default(Nullable<int>);
					}
					this.SendPropertyChanged("CLIENTE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VENDEDORE_PEDIDO", Storage="_VENDEDORE", ThisKey="CODVEN", OtherKey="CODVEN", IsForeignKey=true)]
		public VENDEDORE VENDEDORE
		{
			get
			{
				return this._VENDEDORE.Entity;
			}
			set
			{
				VENDEDORE previousValue = this._VENDEDORE.Entity;
				if (((previousValue != value) 
							|| (this._VENDEDORE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VENDEDORE.Entity = null;
						previousValue.PEDIDOs.Remove(this);
					}
					this._VENDEDORE.Entity = value;
					if ((value != null))
					{
						value.PEDIDOs.Add(this);
						this._CODVEN = value.CODVEN;
					}
					else
					{
						this._CODVEN = default(Nullable<short>);
					}
					this.SendPropertyChanged("VENDEDORE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ITENSPEDIDOs(ITENSPEDIDO entity)
		{
			this.SendPropertyChanging();
			entity.PEDIDO = this;
		}
		
		private void detach_ITENSPEDIDOs(ITENSPEDIDO entity)
		{
			this.SendPropertyChanging();
			entity.PEDIDO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VENDEDORES")]
	public partial class VENDEDORE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _CODVEN;
		
		private string _NOME;
		
		private string _FANTASIA;
		
		private string _ENDERECO;
		
		private string _BAIRRO;
		
		private string _CIDADE;
		
		private string _ESTADO;
		
		private string _CEP;
		
		private string _CPF;
		
		private string _RG;
		
		private string _FONE;
		
		private string _FAX;
		
		private string _E_MAIL;
		
		private System.Nullable<System.DateTime> _DATA_CAD;
		
		private System.Nullable<System.DateTime> _DATA_NASC;
		
		private System.Nullable<decimal> _PORC_COMISSAO;
		
		private EntitySet<PEDIDO> _PEDIDOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODVENChanging(short value);
    partial void OnCODVENChanged();
    partial void OnNOMEChanging(string value);
    partial void OnNOMEChanged();
    partial void OnFANTASIAChanging(string value);
    partial void OnFANTASIAChanged();
    partial void OnENDERECOChanging(string value);
    partial void OnENDERECOChanged();
    partial void OnBAIRROChanging(string value);
    partial void OnBAIRROChanged();
    partial void OnCIDADEChanging(string value);
    partial void OnCIDADEChanged();
    partial void OnESTADOChanging(string value);
    partial void OnESTADOChanged();
    partial void OnCEPChanging(string value);
    partial void OnCEPChanged();
    partial void OnCPFChanging(string value);
    partial void OnCPFChanged();
    partial void OnRGChanging(string value);
    partial void OnRGChanged();
    partial void OnFONEChanging(string value);
    partial void OnFONEChanged();
    partial void OnFAXChanging(string value);
    partial void OnFAXChanged();
    partial void OnE_MAILChanging(string value);
    partial void OnE_MAILChanged();
    partial void OnDATA_CADChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_CADChanged();
    partial void OnDATA_NASCChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_NASCChanged();
    partial void OnPORC_COMISSAOChanging(System.Nullable<decimal> value);
    partial void OnPORC_COMISSAOChanged();
    #endregion
		
		public VENDEDORE()
		{
			this._PEDIDOs = new EntitySet<PEDIDO>(new Action<PEDIDO>(this.attach_PEDIDOs), new Action<PEDIDO>(this.detach_PEDIDOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODVEN", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short CODVEN
		{
			get
			{
				return this._CODVEN;
			}
			set
			{
				if ((this._CODVEN != value))
				{
					this.OnCODVENChanging(value);
					this.SendPropertyChanging();
					this._CODVEN = value;
					this.SendPropertyChanged("CODVEN");
					this.OnCODVENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME", DbType="VarChar(50)")]
		public string NOME
		{
			get
			{
				return this._NOME;
			}
			set
			{
				if ((this._NOME != value))
				{
					this.OnNOMEChanging(value);
					this.SendPropertyChanging();
					this._NOME = value;
					this.SendPropertyChanged("NOME");
					this.OnNOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FANTASIA", DbType="VarChar(20)")]
		public string FANTASIA
		{
			get
			{
				return this._FANTASIA;
			}
			set
			{
				if ((this._FANTASIA != value))
				{
					this.OnFANTASIAChanging(value);
					this.SendPropertyChanging();
					this._FANTASIA = value;
					this.SendPropertyChanged("FANTASIA");
					this.OnFANTASIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDERECO", DbType="VarChar(60)")]
		public string ENDERECO
		{
			get
			{
				return this._ENDERECO;
			}
			set
			{
				if ((this._ENDERECO != value))
				{
					this.OnENDERECOChanging(value);
					this.SendPropertyChanging();
					this._ENDERECO = value;
					this.SendPropertyChanged("ENDERECO");
					this.OnENDERECOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAIRRO", DbType="VarChar(20)")]
		public string BAIRRO
		{
			get
			{
				return this._BAIRRO;
			}
			set
			{
				if ((this._BAIRRO != value))
				{
					this.OnBAIRROChanging(value);
					this.SendPropertyChanging();
					this._BAIRRO = value;
					this.SendPropertyChanged("BAIRRO");
					this.OnBAIRROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIDADE", DbType="VarChar(20)")]
		public string CIDADE
		{
			get
			{
				return this._CIDADE;
			}
			set
			{
				if ((this._CIDADE != value))
				{
					this.OnCIDADEChanging(value);
					this.SendPropertyChanging();
					this._CIDADE = value;
					this.SendPropertyChanged("CIDADE");
					this.OnCIDADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="VarChar(2)")]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this.OnESTADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO = value;
					this.SendPropertyChanged("ESTADO");
					this.OnESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="VarChar(8)")]
		public string CEP
		{
			get
			{
				return this._CEP;
			}
			set
			{
				if ((this._CEP != value))
				{
					this.OnCEPChanging(value);
					this.SendPropertyChanging();
					this._CEP = value;
					this.SendPropertyChanged("CEP");
					this.OnCEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF", DbType="VarChar(18)")]
		public string CPF
		{
			get
			{
				return this._CPF;
			}
			set
			{
				if ((this._CPF != value))
				{
					this.OnCPFChanging(value);
					this.SendPropertyChanging();
					this._CPF = value;
					this.SendPropertyChanged("CPF");
					this.OnCPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RG", DbType="VarChar(15)")]
		public string RG
		{
			get
			{
				return this._RG;
			}
			set
			{
				if ((this._RG != value))
				{
					this.OnRGChanging(value);
					this.SendPropertyChanging();
					this._RG = value;
					this.SendPropertyChanged("RG");
					this.OnRGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FONE", DbType="VarChar(15)")]
		public string FONE
		{
			get
			{
				return this._FONE;
			}
			set
			{
				if ((this._FONE != value))
				{
					this.OnFONEChanging(value);
					this.SendPropertyChanging();
					this._FONE = value;
					this.SendPropertyChanged("FONE");
					this.OnFONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX", DbType="VarChar(15)")]
		public string FAX
		{
			get
			{
				return this._FAX;
			}
			set
			{
				if ((this._FAX != value))
				{
					this.OnFAXChanging(value);
					this.SendPropertyChanging();
					this._FAX = value;
					this.SendPropertyChanged("FAX");
					this.OnFAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_MAIL", DbType="VarChar(35)")]
		public string E_MAIL
		{
			get
			{
				return this._E_MAIL;
			}
			set
			{
				if ((this._E_MAIL != value))
				{
					this.OnE_MAILChanging(value);
					this.SendPropertyChanging();
					this._E_MAIL = value;
					this.SendPropertyChanged("E_MAIL");
					this.OnE_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_CAD", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA_CAD
		{
			get
			{
				return this._DATA_CAD;
			}
			set
			{
				if ((this._DATA_CAD != value))
				{
					this.OnDATA_CADChanging(value);
					this.SendPropertyChanging();
					this._DATA_CAD = value;
					this.SendPropertyChanged("DATA_CAD");
					this.OnDATA_CADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_NASC", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA_NASC
		{
			get
			{
				return this._DATA_NASC;
			}
			set
			{
				if ((this._DATA_NASC != value))
				{
					this.OnDATA_NASCChanging(value);
					this.SendPropertyChanging();
					this._DATA_NASC = value;
					this.SendPropertyChanged("DATA_NASC");
					this.OnDATA_NASCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PORC_COMISSAO", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PORC_COMISSAO
		{
			get
			{
				return this._PORC_COMISSAO;
			}
			set
			{
				if ((this._PORC_COMISSAO != value))
				{
					this.OnPORC_COMISSAOChanging(value);
					this.SendPropertyChanging();
					this._PORC_COMISSAO = value;
					this.SendPropertyChanged("PORC_COMISSAO");
					this.OnPORC_COMISSAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VENDEDORE_PEDIDO", Storage="_PEDIDOs", ThisKey="CODVEN", OtherKey="CODVEN")]
		public EntitySet<PEDIDO> PEDIDOs
		{
			get
			{
				return this._PEDIDOs;
			}
			set
			{
				this._PEDIDOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PEDIDOs(PEDIDO entity)
		{
			this.SendPropertyChanging();
			entity.VENDEDORE = this;
		}
		
		private void detach_PEDIDOs(PEDIDO entity)
		{
			this.SendPropertyChanging();
			entity.VENDEDORE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ITENSPEDIDO")]
	public partial class ITENSPEDIDO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NUM_PEDIDO;
		
		private short _NUM_ITEM;
		
		private System.Nullable<int> _ID_PRODUTO;
		
		private string _COD_PRODUTO;
		
		private System.Nullable<short> _CODCOR;
		
		private System.Nullable<int> _QUANTIDADE;
		
		private System.Nullable<decimal> _PR_UNITARIO;
		
		private System.Nullable<System.DateTime> _DATA_ENTREGA;
		
		private string _SITUACAO;
		
		private System.Nullable<double> _DESCONTO;
		
		private EntityRef<PEDIDO> _PEDIDO;
		
		private EntityRef<PRODUTO> _PRODUTO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNUM_PEDIDOChanging(int value);
    partial void OnNUM_PEDIDOChanged();
    partial void OnNUM_ITEMChanging(short value);
    partial void OnNUM_ITEMChanged();
    partial void OnID_PRODUTOChanging(System.Nullable<int> value);
    partial void OnID_PRODUTOChanged();
    partial void OnCOD_PRODUTOChanging(string value);
    partial void OnCOD_PRODUTOChanged();
    partial void OnCODCORChanging(System.Nullable<short> value);
    partial void OnCODCORChanged();
    partial void OnQUANTIDADEChanging(System.Nullable<int> value);
    partial void OnQUANTIDADEChanged();
    partial void OnPR_UNITARIOChanging(System.Nullable<decimal> value);
    partial void OnPR_UNITARIOChanged();
    partial void OnDATA_ENTREGAChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_ENTREGAChanged();
    partial void OnSITUACAOChanging(string value);
    partial void OnSITUACAOChanged();
    partial void OnDESCONTOChanging(System.Nullable<double> value);
    partial void OnDESCONTOChanged();
    #endregion
		
		public ITENSPEDIDO()
		{
			this._PEDIDO = default(EntityRef<PEDIDO>);
			this._PRODUTO = default(EntityRef<PRODUTO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUM_PEDIDO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int NUM_PEDIDO
		{
			get
			{
				return this._NUM_PEDIDO;
			}
			set
			{
				if ((this._NUM_PEDIDO != value))
				{
					if (this._PEDIDO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNUM_PEDIDOChanging(value);
					this.SendPropertyChanging();
					this._NUM_PEDIDO = value;
					this.SendPropertyChanged("NUM_PEDIDO");
					this.OnNUM_PEDIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUM_ITEM", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short NUM_ITEM
		{
			get
			{
				return this._NUM_ITEM;
			}
			set
			{
				if ((this._NUM_ITEM != value))
				{
					this.OnNUM_ITEMChanging(value);
					this.SendPropertyChanging();
					this._NUM_ITEM = value;
					this.SendPropertyChanged("NUM_ITEM");
					this.OnNUM_ITEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUTO", DbType="Int")]
		public System.Nullable<int> ID_PRODUTO
		{
			get
			{
				return this._ID_PRODUTO;
			}
			set
			{
				if ((this._ID_PRODUTO != value))
				{
					if (this._PRODUTO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PRODUTOChanging(value);
					this.SendPropertyChanging();
					this._ID_PRODUTO = value;
					this.SendPropertyChanged("ID_PRODUTO");
					this.OnID_PRODUTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD_PRODUTO", DbType="VarChar(13)")]
		public string COD_PRODUTO
		{
			get
			{
				return this._COD_PRODUTO;
			}
			set
			{
				if ((this._COD_PRODUTO != value))
				{
					this.OnCOD_PRODUTOChanging(value);
					this.SendPropertyChanging();
					this._COD_PRODUTO = value;
					this.SendPropertyChanged("COD_PRODUTO");
					this.OnCOD_PRODUTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODCOR", DbType="SmallInt")]
		public System.Nullable<short> CODCOR
		{
			get
			{
				return this._CODCOR;
			}
			set
			{
				if ((this._CODCOR != value))
				{
					this.OnCODCORChanging(value);
					this.SendPropertyChanging();
					this._CODCOR = value;
					this.SendPropertyChanged("CODCOR");
					this.OnCODCORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTIDADE", DbType="Int")]
		public System.Nullable<int> QUANTIDADE
		{
			get
			{
				return this._QUANTIDADE;
			}
			set
			{
				if ((this._QUANTIDADE != value))
				{
					this.OnQUANTIDADEChanging(value);
					this.SendPropertyChanging();
					this._QUANTIDADE = value;
					this.SendPropertyChanged("QUANTIDADE");
					this.OnQUANTIDADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_UNITARIO", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> PR_UNITARIO
		{
			get
			{
				return this._PR_UNITARIO;
			}
			set
			{
				if ((this._PR_UNITARIO != value))
				{
					this.OnPR_UNITARIOChanging(value);
					this.SendPropertyChanging();
					this._PR_UNITARIO = value;
					this.SendPropertyChanged("PR_UNITARIO");
					this.OnPR_UNITARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_ENTREGA", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA_ENTREGA
		{
			get
			{
				return this._DATA_ENTREGA;
			}
			set
			{
				if ((this._DATA_ENTREGA != value))
				{
					this.OnDATA_ENTREGAChanging(value);
					this.SendPropertyChanging();
					this._DATA_ENTREGA = value;
					this.SendPropertyChanged("DATA_ENTREGA");
					this.OnDATA_ENTREGAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITUACAO", DbType="VarChar(1)")]
		public string SITUACAO
		{
			get
			{
				return this._SITUACAO;
			}
			set
			{
				if ((this._SITUACAO != value))
				{
					this.OnSITUACAOChanging(value);
					this.SendPropertyChanging();
					this._SITUACAO = value;
					this.SendPropertyChanged("SITUACAO");
					this.OnSITUACAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCONTO", DbType="Float")]
		public System.Nullable<double> DESCONTO
		{
			get
			{
				return this._DESCONTO;
			}
			set
			{
				if ((this._DESCONTO != value))
				{
					this.OnDESCONTOChanging(value);
					this.SendPropertyChanging();
					this._DESCONTO = value;
					this.SendPropertyChanged("DESCONTO");
					this.OnDESCONTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PEDIDO_ITENSPEDIDO", Storage="_PEDIDO", ThisKey="NUM_PEDIDO", OtherKey="NUM_PEDIDO", IsForeignKey=true)]
		public PEDIDO PEDIDO
		{
			get
			{
				return this._PEDIDO.Entity;
			}
			set
			{
				PEDIDO previousValue = this._PEDIDO.Entity;
				if (((previousValue != value) 
							|| (this._PEDIDO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PEDIDO.Entity = null;
						previousValue.ITENSPEDIDOs.Remove(this);
					}
					this._PEDIDO.Entity = value;
					if ((value != null))
					{
						value.ITENSPEDIDOs.Add(this);
						this._NUM_PEDIDO = value.NUM_PEDIDO;
					}
					else
					{
						this._NUM_PEDIDO = default(int);
					}
					this.SendPropertyChanged("PEDIDO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUTO_ITENSPEDIDO", Storage="_PRODUTO", ThisKey="ID_PRODUTO", OtherKey="ID_PRODUTO", IsForeignKey=true)]
		public PRODUTO PRODUTO
		{
			get
			{
				return this._PRODUTO.Entity;
			}
			set
			{
				PRODUTO previousValue = this._PRODUTO.Entity;
				if (((previousValue != value) 
							|| (this._PRODUTO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PRODUTO.Entity = null;
						previousValue.ITENSPEDIDOs.Remove(this);
					}
					this._PRODUTO.Entity = value;
					if ((value != null))
					{
						value.ITENSPEDIDOs.Add(this);
						this._ID_PRODUTO = value.ID_PRODUTO;
					}
					else
					{
						this._ID_PRODUTO = default(Nullable<int>);
					}
					this.SendPropertyChanged("PRODUTO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRODUTOS")]
	public partial class PRODUTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_PRODUTO;
		
		private string _COD_PRODUTO;
		
		private string _DESCRICAO;
		
		private System.Nullable<short> _COD_UNIDADE;
		
		private System.Nullable<short> _COD_TIPO;
		
		private System.Nullable<decimal> _PRECO_CUSTO;
		
		private System.Nullable<decimal> _PRECO_VENDA;
		
		private System.Nullable<int> _QTD_ESTIMADA;
		
		private System.Nullable<int> _QTD_REAL;
		
		private System.Nullable<int> _QTD_MINIMA;
		
		private string _CLAS_FISC;
		
		private System.Nullable<int> _IPI;
		
		private System.Nullable<decimal> _PESO_LIQ;
		
		private EntitySet<ITENSPEDIDO> _ITENSPEDIDOs;
		
		private EntityRef<TIPOPRODUTO> _TIPOPRODUTO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PRODUTOChanging(int value);
    partial void OnID_PRODUTOChanged();
    partial void OnCOD_PRODUTOChanging(string value);
    partial void OnCOD_PRODUTOChanged();
    partial void OnDESCRICAOChanging(string value);
    partial void OnDESCRICAOChanged();
    partial void OnCOD_UNIDADEChanging(System.Nullable<short> value);
    partial void OnCOD_UNIDADEChanged();
    partial void OnCOD_TIPOChanging(System.Nullable<short> value);
    partial void OnCOD_TIPOChanged();
    partial void OnPRECO_CUSTOChanging(System.Nullable<decimal> value);
    partial void OnPRECO_CUSTOChanged();
    partial void OnPRECO_VENDAChanging(System.Nullable<decimal> value);
    partial void OnPRECO_VENDAChanged();
    partial void OnQTD_ESTIMADAChanging(System.Nullable<int> value);
    partial void OnQTD_ESTIMADAChanged();
    partial void OnQTD_REALChanging(System.Nullable<int> value);
    partial void OnQTD_REALChanged();
    partial void OnQTD_MINIMAChanging(System.Nullable<int> value);
    partial void OnQTD_MINIMAChanged();
    partial void OnCLAS_FISCChanging(string value);
    partial void OnCLAS_FISCChanged();
    partial void OnIPIChanging(System.Nullable<int> value);
    partial void OnIPIChanged();
    partial void OnPESO_LIQChanging(System.Nullable<decimal> value);
    partial void OnPESO_LIQChanged();
    #endregion
		
		public PRODUTO()
		{
			this._ITENSPEDIDOs = new EntitySet<ITENSPEDIDO>(new Action<ITENSPEDIDO>(this.attach_ITENSPEDIDOs), new Action<ITENSPEDIDO>(this.detach_ITENSPEDIDOs));
			this._TIPOPRODUTO = default(EntityRef<TIPOPRODUTO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUTO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_PRODUTO
		{
			get
			{
				return this._ID_PRODUTO;
			}
			set
			{
				if ((this._ID_PRODUTO != value))
				{
					this.OnID_PRODUTOChanging(value);
					this.SendPropertyChanging();
					this._ID_PRODUTO = value;
					this.SendPropertyChanged("ID_PRODUTO");
					this.OnID_PRODUTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD_PRODUTO", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string COD_PRODUTO
		{
			get
			{
				return this._COD_PRODUTO;
			}
			set
			{
				if ((this._COD_PRODUTO != value))
				{
					this.OnCOD_PRODUTOChanging(value);
					this.SendPropertyChanging();
					this._COD_PRODUTO = value;
					this.SendPropertyChanged("COD_PRODUTO");
					this.OnCOD_PRODUTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRICAO", DbType="VarChar(40)")]
		public string DESCRICAO
		{
			get
			{
				return this._DESCRICAO;
			}
			set
			{
				if ((this._DESCRICAO != value))
				{
					this.OnDESCRICAOChanging(value);
					this.SendPropertyChanging();
					this._DESCRICAO = value;
					this.SendPropertyChanged("DESCRICAO");
					this.OnDESCRICAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD_UNIDADE", DbType="SmallInt")]
		public System.Nullable<short> COD_UNIDADE
		{
			get
			{
				return this._COD_UNIDADE;
			}
			set
			{
				if ((this._COD_UNIDADE != value))
				{
					this.OnCOD_UNIDADEChanging(value);
					this.SendPropertyChanging();
					this._COD_UNIDADE = value;
					this.SendPropertyChanged("COD_UNIDADE");
					this.OnCOD_UNIDADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD_TIPO", DbType="SmallInt")]
		public System.Nullable<short> COD_TIPO
		{
			get
			{
				return this._COD_TIPO;
			}
			set
			{
				if ((this._COD_TIPO != value))
				{
					if (this._TIPOPRODUTO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCOD_TIPOChanging(value);
					this.SendPropertyChanging();
					this._COD_TIPO = value;
					this.SendPropertyChanged("COD_TIPO");
					this.OnCOD_TIPOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECO_CUSTO", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> PRECO_CUSTO
		{
			get
			{
				return this._PRECO_CUSTO;
			}
			set
			{
				if ((this._PRECO_CUSTO != value))
				{
					this.OnPRECO_CUSTOChanging(value);
					this.SendPropertyChanging();
					this._PRECO_CUSTO = value;
					this.SendPropertyChanged("PRECO_CUSTO");
					this.OnPRECO_CUSTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECO_VENDA", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> PRECO_VENDA
		{
			get
			{
				return this._PRECO_VENDA;
			}
			set
			{
				if ((this._PRECO_VENDA != value))
				{
					this.OnPRECO_VENDAChanging(value);
					this.SendPropertyChanging();
					this._PRECO_VENDA = value;
					this.SendPropertyChanged("PRECO_VENDA");
					this.OnPRECO_VENDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTD_ESTIMADA", DbType="Int")]
		public System.Nullable<int> QTD_ESTIMADA
		{
			get
			{
				return this._QTD_ESTIMADA;
			}
			set
			{
				if ((this._QTD_ESTIMADA != value))
				{
					this.OnQTD_ESTIMADAChanging(value);
					this.SendPropertyChanging();
					this._QTD_ESTIMADA = value;
					this.SendPropertyChanged("QTD_ESTIMADA");
					this.OnQTD_ESTIMADAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTD_REAL", DbType="Int")]
		public System.Nullable<int> QTD_REAL
		{
			get
			{
				return this._QTD_REAL;
			}
			set
			{
				if ((this._QTD_REAL != value))
				{
					this.OnQTD_REALChanging(value);
					this.SendPropertyChanging();
					this._QTD_REAL = value;
					this.SendPropertyChanged("QTD_REAL");
					this.OnQTD_REALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTD_MINIMA", DbType="Int")]
		public System.Nullable<int> QTD_MINIMA
		{
			get
			{
				return this._QTD_MINIMA;
			}
			set
			{
				if ((this._QTD_MINIMA != value))
				{
					this.OnQTD_MINIMAChanging(value);
					this.SendPropertyChanging();
					this._QTD_MINIMA = value;
					this.SendPropertyChanged("QTD_MINIMA");
					this.OnQTD_MINIMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLAS_FISC", DbType="VarChar(10)")]
		public string CLAS_FISC
		{
			get
			{
				return this._CLAS_FISC;
			}
			set
			{
				if ((this._CLAS_FISC != value))
				{
					this.OnCLAS_FISCChanging(value);
					this.SendPropertyChanging();
					this._CLAS_FISC = value;
					this.SendPropertyChanged("CLAS_FISC");
					this.OnCLAS_FISCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPI", DbType="Int")]
		public System.Nullable<int> IPI
		{
			get
			{
				return this._IPI;
			}
			set
			{
				if ((this._IPI != value))
				{
					this.OnIPIChanging(value);
					this.SendPropertyChanging();
					this._IPI = value;
					this.SendPropertyChanged("IPI");
					this.OnIPIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PESO_LIQ", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> PESO_LIQ
		{
			get
			{
				return this._PESO_LIQ;
			}
			set
			{
				if ((this._PESO_LIQ != value))
				{
					this.OnPESO_LIQChanging(value);
					this.SendPropertyChanging();
					this._PESO_LIQ = value;
					this.SendPropertyChanged("PESO_LIQ");
					this.OnPESO_LIQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUTO_ITENSPEDIDO", Storage="_ITENSPEDIDOs", ThisKey="ID_PRODUTO", OtherKey="ID_PRODUTO")]
		public EntitySet<ITENSPEDIDO> ITENSPEDIDOs
		{
			get
			{
				return this._ITENSPEDIDOs;
			}
			set
			{
				this._ITENSPEDIDOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TIPOPRODUTO_PRODUTO", Storage="_TIPOPRODUTO", ThisKey="COD_TIPO", OtherKey="COD_TIPO", IsForeignKey=true)]
		public TIPOPRODUTO TIPOPRODUTO
		{
			get
			{
				return this._TIPOPRODUTO.Entity;
			}
			set
			{
				TIPOPRODUTO previousValue = this._TIPOPRODUTO.Entity;
				if (((previousValue != value) 
							|| (this._TIPOPRODUTO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TIPOPRODUTO.Entity = null;
						previousValue.PRODUTOs.Remove(this);
					}
					this._TIPOPRODUTO.Entity = value;
					if ((value != null))
					{
						value.PRODUTOs.Add(this);
						this._COD_TIPO = value.COD_TIPO;
					}
					else
					{
						this._COD_TIPO = default(Nullable<short>);
					}
					this.SendPropertyChanged("TIPOPRODUTO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ITENSPEDIDOs(ITENSPEDIDO entity)
		{
			this.SendPropertyChanging();
			entity.PRODUTO = this;
		}
		
		private void detach_ITENSPEDIDOs(ITENSPEDIDO entity)
		{
			this.SendPropertyChanging();
			entity.PRODUTO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TIPOPRODUTO")]
	public partial class TIPOPRODUTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _COD_TIPO;
		
		private string _TIPO;
		
		private EntitySet<PRODUTO> _PRODUTOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCOD_TIPOChanging(short value);
    partial void OnCOD_TIPOChanged();
    partial void OnTIPOChanging(string value);
    partial void OnTIPOChanged();
    #endregion
		
		public TIPOPRODUTO()
		{
			this._PRODUTOs = new EntitySet<PRODUTO>(new Action<PRODUTO>(this.attach_PRODUTOs), new Action<PRODUTO>(this.detach_PRODUTOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD_TIPO", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short COD_TIPO
		{
			get
			{
				return this._COD_TIPO;
			}
			set
			{
				if ((this._COD_TIPO != value))
				{
					this.OnCOD_TIPOChanging(value);
					this.SendPropertyChanging();
					this._COD_TIPO = value;
					this.SendPropertyChanged("COD_TIPO");
					this.OnCOD_TIPOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO", DbType="VarChar(30)")]
		public string TIPO
		{
			get
			{
				return this._TIPO;
			}
			set
			{
				if ((this._TIPO != value))
				{
					this.OnTIPOChanging(value);
					this.SendPropertyChanging();
					this._TIPO = value;
					this.SendPropertyChanged("TIPO");
					this.OnTIPOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TIPOPRODUTO_PRODUTO", Storage="_PRODUTOs", ThisKey="COD_TIPO", OtherKey="COD_TIPO")]
		public EntitySet<PRODUTO> PRODUTOs
		{
			get
			{
				return this._PRODUTOs;
			}
			set
			{
				this._PRODUTOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PRODUTOs(PRODUTO entity)
		{
			this.SendPropertyChanging();
			entity.TIPOPRODUTO = this;
		}
		
		private void detach_PRODUTOs(PRODUTO entity)
		{
			this.SendPropertyChanging();
			entity.TIPOPRODUTO = null;
		}
	}
}
#pragma warning restore 1591
